import { useEffect, useState } from 'react';
import { command, type Snapshot } from './bridge';
type Draft = { id: string; name: string; domains: string };
const toDraft = (r: { id: string; name: string; domains: string[] }): Draft => ({ id: r.id, name: r.name, domains: r.domains.join(', ') });
export function WebsiteRules({ state }: { state: Snapshot }) {
  const source = JSON.stringify(state.settings.websiteProjects), [rules, setRules] = useState(state.settings.websiteProjects ?? []);
  const [draft, setDraft] = useState<Draft | null>(null), [busy, setBusy] = useState(false), [message, setMessage] = useState('');
  useEffect(() => setRules(state.settings.websiteProjects ?? []), [source]);
  const save = async (event: React.FormEvent) => { event.preventDefault(); if (!draft) return; const domains = draft.domains.split(/[,，\s]+/).filter(Boolean).map(d => d.toLowerCase().replace(/\.$/, '')); setBusy(true); try { const next = rules.some(r => r.id === draft.id) ? rules.map(r => r.id === draft.id ? { id: draft.id, name: draft.name.trim(), domains } : r) : [...rules, { id: draft.id, name: draft.name.trim(), domains }]; await command('settings', { settings: { ...state.settings, websiteRules: null, websiteProjects: next } }); setRules(next); setDraft(null); setMessage('已保存，之后的新记录使用新规则。'); } catch (e) { setMessage(e instanceof Error ? e.message : '保存失败'); } finally { setBusy(false); } };
  const remove = async (id: string) => { const next = rules.filter(r => r.id !== id); setBusy(true); try { await command('settings', { settings: { ...state.settings, websiteRules: null, websiteProjects: next } }); setRules(next); setMessage('已删除，之后的新记录不再使用这项归属。'); } catch (e) { setMessage(e instanceof Error ? e.message : '删除失败'); } finally { setBusy(false); } };
  return <section className="panel history settings website-projects"><div className="settings-card-header"><div><span className="eyebrow">网站归属</span><h2>把常用网站，放回它们的项目里</h2><p>记录发生时决定归属，同一项目可覆盖多个域名，三种浏览器自动合并。</p></div><span className="settings-count">{rules.length} / 50</span></div><div className="settings-note"><strong>只影响未来</strong><span>保存后的新记录使用新规则；之前的名称、归属和来源浏览器都会保留。</span></div><div className="website-project-list">{rules.map((r, i) => <div className="website-project-item" key={r.id}><span className="project-index">{String(i + 1).padStart(2, '0')}</span><div className="project-summary"><strong>{r.name}</strong><span>{r.domains.join(' · ')}</span></div><div className="project-actions"><button type="button" disabled={busy} onClick={() => setDraft(toDraft(r))}>编辑</button><button type="button" disabled={busy} onClick={() => void remove(r.id)}>删除</button></div></div>)}</div>{!rules.length && <p className="empty project-empty">还没有网站归属，匹配的网站会计入浏览器。</p>}<div className="website-project-actions"><button type="button" disabled={busy || rules.length >= 50} onClick={() => setDraft({ id: crypto.randomUUID(), name: '', domains: '' })}>＋ 添加网站应用</button>{message && <p role="status">{message}</p>}</div>{draft && <div className="overlay project-overlay" onMouseDown={e => { if (e.target === e.currentTarget && !busy) setDraft(null); }}><form className="modal project-modal" onSubmit={save}><div className="section-head"><div><span className="eyebrow">网站归属</span><h2>{rules.some(r => r.id === draft.id) ? '编辑网站应用' : '添加网站应用'}</h2></div><button type="button" aria-label="关闭" onClick={() => setDraft(null)}>×</button></div><p>名称会显示在应用统计中。多个域名用逗号分隔，自动包含其子域名。</p><label>显示名称<input autoFocus required maxLength={80} placeholder="例如：B站" value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })} /></label><label>归属域名<input required placeholder="bilibili.com, example.com" value={draft.domains} onChange={e => setDraft({ ...draft, domains: e.target.value })} /></label><div className="modal-footer"><button type="button" disabled={busy} onClick={() => setDraft(null)}>取消</button><button className="primary" disabled={busy}>保存归属</button></div></form></div>}</section>;
}
